

services:
  mongo:
    image: mongo:6
    container_name: mongo_db
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${NAME}
      MONGO_INITDB_ROOT_PASSWORD: ${PASSWORD}

      
    volumes:
      - mongo_data:/data/db

  app:
    build: .
    container_name: node_app
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - mongo
volumes:
  mongo_data:

